SrfGen/srfinfo2vm.py
pgv target set from magnitude
tested, seems fine
=> default mag2pgv target

SrfGen/srfinfo2vm.py
dependency of srfinfo2vm from post-processing to Empirical_Engine
=> Dependency

SrfGen/createSRF.py, SrfGen/createSourceRealisation.py, SrfGen/srf_config.py
Removed constants from srf_config
=> Changed createSRF to use the new binary versioning system in qcore

CHANGELOG.md, SrfGen/srfinfo2vm.py
Corrected method of oversize detection
=> Add changelog

SrfGen/createSRF.py
fix the line attempting to find a binary using old way
=> Binary find bug fix

CHANGELOG.md, SrfGen/createSourceRealisation.py
Mean must be given as a string with 4 leading and one trailing character
=> Add truncated log normal distribution

SrfGen/createSourceRealisation.py
=> Fix formula

SrfGen/NHM/nhm2srf.py, SrfGen/createSRF.py
Currently cannot accept multiple realisations to generate.
=> Refactor nhm2srf to be used by one realisation at a time.

.gitignore, .travis.yml, SrfGen/NHM/fault_realisation_selection.py, SrfGen/NHM/find_short_segments.py, SrfGen/NHM/nhm2leonard.py, SrfGen/NHM/nhm2selection.py, SrfGen/NHM/nhm2srf.py, SrfGen/NHM/plot_nhm_outputs.py, SrfGen/createSourceRealisation.py, SrfGen/gcmt2srf.py, SrfGen/srf_config.py, SrfGen/srfinfo2vm.py, requirements.txt, test/test_gen_coords/test_gen_coords.py
added black, but test_gen_corrds not working hence commented out
=> added black

SrfGen/srfinfo2vm.py
=> Code doesn't execute

CHANGELOG.md, SrfGen/NHM/nhm2srf.py, SrfGen/createSRF.py
Old code changes that never made it in.
Some updates have been made
=> Subduction srfgen

srf_generation/source_parameter_generation/gcmt_to_realisation.py, srf_generation/source_parameter_generation/uncertainties/perturbation_template.py.template, srf_generation/source_parameter_generation/uncertainties/versions/V19p8.py, srf_generation/source_parameter_generation/uncertainties/versions/unperturbated.py
Add ability to make source specific parameters.
Added kwargs to perturbation functions so old versions remain compatible with the workflow, even if updates mean additional arguments are passed to perturbation scripts
=> Source specific params

srf_generation/source_parameter_generation/generate_realisations_from_gcmt.py
gcmt to realisation orchestration script
Added more argument help text
=> Added ability to generate single realisations without rel numbers to the

srf_generation/input_file_generation/realisation_to_srf.py
=> Fixed genslip version checking so that versions other than 3.3 will

srf_generation/Fault.py, srf_generation/pre_processing_common.py, srf_generation/source_parameter_generation/uncertainties/common.py, srf_generation/source_parameter_generation/uncertainties/mag_scaling.py, srf_generation/source_parameter_generation/uncertainties/perturbation_template.py.template, srf_generation/source_parameter_generation/uncertainties/versions/gcmt_1.py, srf_generation/source_parameter_generation/uncertainties/versions/gcmt_2.py, test/test_gen_coords/test_gen_coords.py, test/test_uncertainties/test_mag_scaling.py
=> Changed Leonard scaling to create non-square fault planes

srf_generation/input_file_generation/realisation_to_srf.py
Tested Realisation to SRF and came across this minor issue. Fixed.
=> Minor bug fix for csv -> srf gen

SrfGen/srfinfo2vm.py
updated novm option to generate vm_corners in the same format as the C
=> -novm option

srf_generation/source_parameter_generation/gcmt_to_realisation.py
Otherwise a dataframe is attempted to be put in a dataframe
=> Remove saved dataframe from dict to be saved

srf_generation/velocity_model_generation/generate_perturbation_file.py
Wiki page with file formats to come
=> Documentation update

geoNet/process_observed.py
Added support for writing unrotated horizontal acceleration components
=> Unrotated horizontal acceleration components

srf_generation/input_file_generation/realisation_to_srf.py
=> Add risetime_coef to type 2 source gen

SrfGen/NHM/GNS_ERF_comparison/gns_erf_comparison.py, srf_generation/source_parameter_generation/uncertainties/mag_scaling.py
Thoughts about merging this in? 
As we aren't using the new relations anywhere anymore.
=> Mag scaling

srf_generation/poly_fault_select.py
not sure on how this will be used so may be some changes wanted?
=> Polyselect

srf_generation/velocity_model_generation/generate_3d_velocity_model_perturbation.py
=> Spelling and ordering mistakes

Jenkinsfile, VM/rel2vm_params.py
=> Creating virtual env

srf_generation/Fault.py, srf_generation/source_parameter_generation/uncertainties/common.py, srf_generation/source_parameter_generation/uncertainties/mag_scaling.py, srf_generation/source_parameter_generation/uncertainties/magnitude_scaling/allen_2017.py, srf_generation/source_parameter_generation/uncertainties/magnitude_scaling/strasser_2010.py, srf_generation/source_parameter_generation/uncertainties/versions/cs_20_4.py, test/test_uncertainties/test_mag_scaling.py
Adding Thingbaijam, Murotani, Blaser, Allen and Strasser models.
Have put Allen and Strasser in separate files to reduce how big the MWSR file is getting
=> Adding more MWSRs

srf_generation/input_file_generation/realisation_to_srf.py
Tested on local with a Hossack SRF. Works well!
=> Use argument parsing rather than stdin/out

VM/vm_params2vm.py, srf_generation/source_parameter_generation/generate_realisations_from_gcmt.py
=> Merging Master into this branch
