- SrfGen/createSRF.py
dimensional lists.
This does not cause issues as nothing reads the rake from the srf info
file, except when it is being read manually.
If in future it is desirable to use rakes from the srfinfo file then a
better solution must be found.
> rake 2d lists are flattened to a 1d array as hdf5 cannot store multi

- SrfGen/srfinfo2vm.py
- srf_generation/input_file_generation/generate_srf_from_realisations.py
- srf_generation/input_file_generation/realisation_to_srf.py
If realisation_to_srf is run then all output files are placed adjacent to the realisation file
if generate_srf_from_realisations is run then output files are placed consistent with the cybershake directory structure
Also fix bug with attempting to pickle loggers for multiprocessed vm generation
srfinfo2vm no longer has special case for single threaded mode
> Change how filepaths are handled.

- srf_generation/input_file_generation/realisation_to_srf.py
If they aren't given then nothing is passed to genslip
These defaults cause wildly incorrect srfs to be generated
> Remove default values for optional parameters

- SrfGen/createSRF.py
Some of our code can't parse version 2.0 of SRF format. So if we are using the latest version we need to make sure we are using version 1.0 rather than implicitly because we are on an old version.
> switched srf_version

- SrfGen/createSRF.py
- SrfGen/gen_coords.py
- SrfGen/srfinfo2vm.py
- srf_generation/Fault.py
- srf_generation/plot_realisation_file_parameters.py
- srf_generation/source_parameter_generation/nhm_to_realisation.py
- srf_generation/source_parameter_generation/uncertainties/common.py
- srf_generation/source_parameter_generation/uncertainties/distributions.py
- srf_generation/source_parameter_generation/uncertainties/mag_scaling.py
- srf_generation/source_parameter_generation/uncertainties/versions/V19p8.py
- srf_generation/source_parameter_generation/uncertainties/versions/cs_20_4.py
- srf_generation/source_parameter_generation/uncertainties/versions/gcmt_1.py
- srf_generation/source_parameter_generation/uncertainties/versions/gcmt_2.py
- srf_generation/source_parameter_generation/uncertainties/versions/nhm_3.py
- srf_generation/source_parameter_generation/uncertainties/versions/nhm_4.py
- srf_generation/source_parameter_generation/uncertainties/versions/sjn_realisations_203.py
Can now edit the risetime parameters for srf generation.
Type 1 generation has one multiplier taper, which defaults from 2* at 5km to 1* at 8km
Type 2-4 generation has two multiplier tapers, which default t o2* at 5km to 1* at 8km and 1* at 15km to 2* at 20km
> Risetime parameters

- SrfGen/srfinfo2vm.py
Newlines weren't printed on VM check pass, giving funky console output
> print instead of sys.stderr

- srf_generation/input_file_generation/realisation_to_srf.py
This change broke previous behaviour as faults generated with rounded edge lengths instead of the length calculated from the mom->area formula
e.g. 2122842 had an edge length of 2.0 instead of 1.7783 as per original Validation generated srfs
> Revert change. Not sure why original change was made

- srf_generation/source_parameter_generation/generate_realisations_from_gcmt.py
faults is a {str:int} dict, with the number of realisations for each event/fault in it.
I have no idea why it tried iterating over the int and not the range in the first place
NHMs don't generate this aggregation file, so don't have the issue
> Bug hunt: Like duck hunt but with less annoying dog

- srf_generation/source_parameter_generation/uncertainties/common.py
This is part of my checks to ensure that version files only add things that are useful to the realisation file
Mostly to prevent spelling mistakes etc, rather than stop weird things going in though
> dbottom was added to type2 gen for VMgen

- VM/rel2vm_params.py
This error occurred with --help option
```
python VM/rel2vm_params.py --help
Traceback (most recent call last):
File "VM/rel2vm_params.py", line 1121, in <module>
args = load_args()
File "VM/rel2vm_params.py", line 1094, in load_args
args = parser.parse_args()
File "/usr/lib/python3.8/argparse.py", line 1768, in parse_args
args, argv = self.parse_known_args(args, namespace)
File "/usr/lib/python3.8/argparse.py", line 1800, in parse_known_args
namespace, args = self._parse_known_args(args, namespace)
File "/usr/lib/python3.8/argparse.py", line 2006, in _parse_known_args
start_index = consume_optional(start_index)
File "/usr/lib/python3.8/argparse.py", line 1946, in consume_optional
take_action(action, args, option_string)
File "/usr/lib/python3.8/argparse.py", line 1874, in take_action …
```
> To represent % in a string, it needs %%

- VM/vm_params2vm.py
vm_params2vm.py had a wrong help for argument --outdir.
If no outdir is specified, use the directory that contains vm_params.yaml, not rel file.
> If outdir is not specified, use the dir containing vm_params.yaml

- srf_generation/source_parameter_generation/uncertainties/versions/nhm_4.py
This means the shyp was being double halved, and therefore restricted to the middle half of faults
> rand_shyp is in the range [-0.5, 0.5]

- srf_generation/input_file_generation/realisation_to_srf.py
This change makes the srfinfo shypo values the same as what is stored in the rel_csv aka internally consistent.
> fixed bug with consistency with srfinfo

- srf_generation/plot_realisation_file_parameters.py
- srf_generation/source_parameter_generation/common.py
- srf_generation/source_parameter_generation/gcmt_to_realisation.py
- srf_generation/source_parameter_generation/generate_realisations_from_gcmt.py
- srf_generation/source_parameter_generation/generate_realisations_from_nhm.py
- srf_generation/source_parameter_generation/nhm_to_realisation.py
- srf_generation/velocity_model_generation/generate_3d_velocity_model_perturbation.py
- srf_generation/velocity_model_generation/generate_perturbation_file.py
Bring script arguments back into parity with gcmt, without losing added funcitonality
> Fix spelling

- srf_generation/source_parameter_generation/nhm_to_realisation.py
It seems we don't usually run nhm_to_realisation directly, so this bug stayed unnoticed.
```
def get_additional_source_parameters(
source_parameters: List[Tuple[str, str]],
common_source_parameters: List[Tuple[str, str]],
nhm_data: Dict[str, NHMFault],  <----
vel_mod_1d_layers: pd.DataFrame,
):
```
`fault_nhm` is an object of NHMFault, so calling this function use to crash.
> Fix: argument's data type matched to function signature

- srf_generation/source_parameter_generation/generate_realisations_from_gcmt.py
When rel num is 0, the selection file has no second column, the ordered_rels list is supposed to collect the fault names.
However, faults[pid] is 0, and the list comprehension is never executed and ordered_rels becomes an empty list.
This patch fixes the issue.
> Fixed: when rel num is 0, it crashes when sorting agg file

- VM/vm_params2vm.py
My bad - my earlier PR (https://github.com/ucgmsim/Pre-processing/pull/221) had a bug.
mkdtemp returns a path in string format, and doesn't have cleanup() function unlike TemporaryDirectory.
> mkdtemp has no cleanup()

- srf_generation/input_file_generation/realisation_to_srf.py
- srf_generation/pre_processing_common.py
This issue was found while tech-supporting Mike.
When a realisation name is all numbers, SRF gen was failing
```
2020p806446_REL01 |         SRF_GEN |  completed | 40773862 |  2023-11-08 23:53:36
2192455 |         SRF_GEN |     failed | 40772343 |  2023-11-08 23:06:43
2192455_REL01 |         SRF_GEN |  completed | 40773243 |  2023-11-08 23:38:03
2474759 |         SRF_GEN |     failed | 40772346 |  2023-11-08 23:06:43
2474759_REL01 |         SRF_GEN |  completed | 40773258 |  2023-11-08 23:38:29
2625245 |         SRF_GEN |     failed | 40772348 |  2023-11-08 23:06:43
2625245_REL01 |         SRF_GEN |  completed | 40773262 |  2023-11-08 23:38:55
2808393 |         SRF_GEN |     failed | 40772350 |  2023-11-08 23:06:43
2808393_REL01 |         SRF_GEN |  completed | 40773263 |  2023-11-08 …
```
> FIX: If rel name is all-number, SRF gen fails

- VM/vm_params2vm.py
- srf_generation/velocity_model_generation/generate_3d_velocity_model_perturbation.py
When VM pert is done as a part of CS workflow and VM pert from config is what you want to do (opposed to from model), it creates layer0.pertb, layer1.pertb... temporary files in the CS root directory.
```
-rw-rw----+   1 baes  nesi00213    10620000 Nov 22 23:26 layer0.pertb
-rw-rw----+   1 baes  nesi00213    42480000 Nov 22 23:26 layer1.pertb
-rw-rw----+   1 baes  nesi00213    31860000 Nov 22 23:26 layer2.pertb
..
-rw-rw----+   1 baes  nesi00213    95580000 Nov 22 23:26 layer3.pertb.cplx
```
When there are multiple VM pert jobs running at the same time, this causes multiple processes trying to read/write the temporary file of the same name in the same location. As a result, many of VM pert jobs would crash, producing core files in the CS root directory.
This can be fixed by creating a …
> FIX: If VM pert from conf, layerX.pertb files are created in CS root dir

- VM/models/AfshariStewart_2016_Ds.py
- VM/models/Bradley_2010_Sa.py
- VM/plot_vm.py
- srf_generation/input_file_generation/realisation_to_srf.py
- srf_generation/source_parameter_generation/uncertainties/versions/V19p8.py
- srf_generation/source_parameter_generation/uncertainties/versions/cs_20_4.py
- srf_generation/source_parameter_generation/uncertainties/versions/feature_showcase.py
- srf_generation/source_parameter_generation/uncertainties/versions/gcmt_1.py
- srf_generation/source_parameter_generation/uncertainties/versions/gcmt_2.py
- srf_generation/source_parameter_generation/uncertainties/versions/nhm_3.py
- srf_generation/source_parameter_generation/uncertainties/versions/nhm_4.py
- srf_generation/source_parameter_generation/uncertainties/versions/sjn_realisations_203.py
- srf_generation/velocity_model_generation/q_model_generation/EP_to_bin.py
- srf_generation/velocity_model_generation/q_model_generation/generate_all_qp_qs.py
Adds documentation, type-hints, consistency checks, and clears out some python no-no's from the realisation to srf code. 
There are a number of outstanding parameters that do not currently have any documentation - because I am not sure what they are. Some input on what these are would be appreciated so I can finish the documentation of the module. Also I would appreciate someone checking my documentation does make sense; I probably misinterpreted what certain variables mean.
I also propose changing the way the parameters yaml object is created (WIP). Currently, this object is creating by taking first the realisation file and then stripping some of the fields out (which is why there is so many pop calls all over the place). This is not a very good way to do things, because it means we are …
> Clean up realisation to SRF generation code (WIP)

- srf_generation/Fault.py
There was a discussion on Leonard2010 vs Leonard2014 on Slack in regards to what we should use for the magnitude-area relations. 
https://uceqeng.slack.com/archives/CUD9MUZ4Y/p1719447280472479
We have been using LEONARD2014 for Cybershake.
Leonard2010 is on active region and Leonard2014 is on SCR (stable continental region), so we should use & cite Leonard2010 for Cybershake NZ.
However, it happens to be the underlying math is the same. 
For the future reference, I just made a comment. 
Perhaps it is better to rename it to Leonard2010 in
https://github.com/ucgmsim/qcore/blob/master/qcore/uncertainties/mag_scaling.py 
but I feel it can be slightly risky when we currently have a Cyberhsake 200m run in progress...
> Updated comment on Leonard2014

- Jenkinsfile
- srf_generation/input_file_generation/realisation_to_srf.py
When you run `realisation_to_srf.py` from the path where the rel csv file is located and give a relative path (ie. just the file name), it will get confused when it sees `mkdir` because `os.path.dirname(rel_csv)` is an empty string.
```
Traceback (most recent call last):
...
File "/home/seb56/Pre-processing/srf_generation/input_file_generation/realisation_to_srf.py", line 88, in create_stoch
os.makedirs(out_dir, exist_ok=True)
File "/home/seb56/miniforge3/envs/mamba310/lib/python3.10/os.py", line 225, in makedirs
mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```
or 
Traceback (most recent call last):
...
File "/home/seb56/Pre-processing/srf_generation/input_file_generation/realisation_to_srf.py", line 1016, in generate_sim_params_yaml …
> Fix for a rel csv file given in relative path
